### ISSUE TITLE
LargeSK critical bug

### ISSUE THREAD

**Issue by GrimEpp** [Nicofisi/LargeSk#3]
This addon has a critical bug that most addon has.
The error is you need to add this in your plugin.yml
depend: [Skellet]
and you need to make every effect umbaska
you also have to use Skellet#FixErrors

**Comment by Nicofisi** [comment]
Your solution is invalid. The only officially supported solution is removing Skellett.

**Comment by GrimEpp** [comment]
No you need 
Skellet#FixErrors

**Comment by Xevryll** [comment]
this is a meme comment

**Comment by GrimEpp** [comment]
No this is a really critical bug!

**Comment by Nicofisi** [comment]
You can pull request deleting every file from Skellett if you want it to be fixed <3

**Comment by Nicofisi** [comment]
Pull request or I'll close it!!!!! Oh noes

**Comment by GrimEpp** [comment]
idk how so idc

**Comment by Nicofisi** [comment]
bai

**Comment by GrimEpp** [comment]
Reopend this is a servious issoe

**Comment by Nicofisi** [comment]
You didn't?
